/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package citivexp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import yahoofinance.Stock;
import yahoofinance.YahooFinance;

class AppTest {
    @Test
    public void testYahooFianceAPI(){
        String symbol = "AAPL";
        try{
         Stock stock = YahooFinance.get(symbol);
         String company = stock.getName();
         double price = stock.getQuote().getPrice().doubleValue();
         double change = stock.getQuote().getChange().doubleValue();
         System.out.println("Company name: " + company);
         System.out.println("Price: " + price);
         System.out.println("Change: " + change);
        }catch (Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }
}
