/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package citivexp;

import yahoofinance.Stock;
import yahoofinance.YahooFinance;
import java.util.*;
public class App {
    private record StockPrice(String symbol, double price, double change,Date timestamp) {
    }
    private static final String DJIA = "DJIA";
    private static final int QUERY_LIMIT = 5000;
    private Queue<StockPrice> stockPriceQueue = new LinkedList<>();

    public void StockPriceTracker(){
        stockPriceQueue = new LinkedList<>();
    }
    public void startTracking(){
        Timer timer = new Timer();
        timer.schedule(new TimerTask(){
            @Override
            public void run() {
                try{
                    double stockPrice = YahooFinance.get(DJIA).getQuote().getPrice().doubleValue();
                    StockPrice stockPriceEntry = new StockPrice("DJIA", stockPrice, stockPrice, new Date());
                    stockPriceQueue.add(stockPriceEntry);
                    System.out.println("Price: " + stockPriceEntry.price+" Change: " + stockPriceEntry.change+" Timestamp: " + stockPriceEntry.timestamp);
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
        },0,QUERY_LIMIT);
    }
    public static void main(String[] args) {
        String stockSymbol = "AAPL";
        try{
            Stock stock = YahooFinance.get(stockSymbol);
            String company = stock.getName();
            double price = stock.getQuote().getPrice().doubleValue();
            double change = stock.getQuote().getChange().doubleValue();
            System.out.println("Company name: " + company);
            System.out.println("Price: " + price);
            System.out.println("Change: " + change);
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }
}
